# downloader.py
import re
import subprocess
import tempfile
from pathlib import Path


class DownloadError(Exception):
    """下载失败时抛出的异常"""
    pass


# yt-dlp 基础参数：启用 EJS 解题器以通过 YouTube 反爬验证
_YT_DLP_BASE = ["yt-dlp", "--remote-components", "ejs:github"]


def _sanitize_filename(name: str) -> str:
    """将视频标题转为安全的文件名"""
    name = re.sub(r'[\\/*?:"<>|]', '', name)
    name = re.sub(r'\s+', '_', name.strip())
    return name[:200] if name else "untitled"


def _write_cookies_file(cookies: list[dict]) -> Path:
    """将 Chrome Extension 传来的 cookies 列表写成 Netscape 格式的临时文件"""
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", prefix="yt2text_cookies_", delete=False
    )
    tmp.write("# Netscape HTTP Cookie File\n")
    tmp.write("# Generated by yt2text Chrome Extension\n\n")
    for c in cookies:
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expirationDate", 0))
        name = c.get("name", "")
        value = c.get("value", "")
        tmp.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
    tmp.close()
    return Path(tmp.name)


def _get_cookie_args(cookies: list[dict] | None, browser: str | None) -> tuple[list[str], Path | None]:
    """返回 (yt-dlp cookie 参数列表, 临时文件路径 or None)
    优先使用 Extension 传来的 cookies，其次 --cookies-from-browser"""
    if cookies:
        cookie_file = _write_cookies_file(cookies)
        print(f"🍪 使用 Chrome Extension cookies ({len(cookies)} 条)")
        return ["--cookies", str(cookie_file)], cookie_file
    if browser:
        print(f"🍪 使用浏览器 cookies: {browser}")
        return ["--cookies-from-browser", browser], None
    return [], None


def _get_video_title(url: str, cookies: list[dict] | None = None, browser: str | None = None) -> str:
    """获取视频标题"""
    cookie_args, cookie_file = _get_cookie_args(cookies, browser)
    command = _YT_DLP_BASE + ["--print", "title", url] + cookie_args

    try:
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        if result.stderr.strip():
            print(f"   ⚠️  yt-dlp stderr: {result.stderr.strip()}")
    finally:
        if cookie_file:
            cookie_file.unlink(missing_ok=True)
    return ""


def _parse_download_error(stderr: str) -> str:
    """解析下载错误并返回友好提示信息"""
    if "members" in stderr.lower() or "member" in stderr.lower():
        return "该视频为频道会员专属内容，需要登录信息才能下载。请确认你已在 Chrome 中登录 YouTube 且为该频道会员。"
    elif "private" in stderr.lower():
        return "该视频为私密视频，无法下载。"
    elif "unavailable" in stderr.lower() or "not available" in stderr.lower():
        return "该视频不可用（可能已被删除或存在地区限制）。"
    else:
        return f"下载失败：{stderr.strip()}"


def download_audio(url: str, output_dir: str = "output", browser: str = None, cookies: list[dict] | None = None, title: str | None = None) -> Path:
    Path(output_dir).mkdir(exist_ok=True)

    # 优先使用 Extension 传来的标题，省去 yt-dlp 取标题的耗时
    if not title:
        print("📋 获取视频标题...")
        title = _get_video_title(url, cookies=cookies, browser=browser)
    if not title:
        print("⚠️  无法获取视频标题，使用默认文件名")
        safe_title = "audio"
    else:
        safe_title = _sanitize_filename(title)
        print(f"   标题: {title}")

    audio_path = Path(output_dir) / f"{safe_title}.opus"

    # 兼容旧缓存：检查 .opus 和 .mp3
    for ext in (".opus", ".mp3"):
        candidate = Path(output_dir) / f"{safe_title}{ext}"
        if candidate.exists() and candidate.stat().st_size > 0:
            print(f"⏩ 音频文件已存在，跳过下载: {candidate}")
            return candidate

    output_template = f"{output_dir}/{safe_title}.%(ext)s"
    cookie_args, cookie_file = _get_cookie_args(cookies, browser)

    command = _YT_DLP_BASE + [
        "-f", "ba[abr<=64]/wa/ba",   # 选最小音频流，语音识别无需高音质
        "-x",
        "--audio-format", "opus",     # 保持 opus 原生格式，跳过 mp3 转码
        "--no-playlist",
        url,
        "-o", output_template,
    ] + cookie_args

    try:
        print(f"   ▶ yt-dlp 开始下载...")
        result = subprocess.run(command, capture_output=True, text=True)
        # 打印 yt-dlp 输出以便诊断耗时
        if result.stdout.strip():
            for line in result.stdout.strip().split("\n"):
                print(f"   [yt-dlp] {line}")
        if result.returncode != 0:
            print(f"   ❌ yt-dlp stderr:\n{result.stderr.strip()}")
            msg = _parse_download_error(result.stderr)
            raise DownloadError(msg)
    finally:
        if cookie_file:
            cookie_file.unlink(missing_ok=True)

    # yt-dlp 实际输出的文件名可能与预期不同，做一次确认
    if not audio_path.exists():
        for ext in (".opus", ".webm", ".m4a", ".ogg", ".mp3"):
            candidate = Path(output_dir) / f"{safe_title}{ext}"
            if candidate.exists() and candidate.stat().st_size > 0:
                audio_path = candidate
                break

    return audio_path
